### ISSUE TITLE
Go OFL

### ISSUE THREAD

**Issue by davelab6** [fontuni/vain#1]
I wonder if you would consider switching from public domain to the SIL Open Font License? :)

**Comment by sungsit** [comment]
What is the benefit of OFL over CC0 when I want people to feel free to do whatsoever they want with this font? 

I've waived my right on it for satirical reasons though, even a stupid font from Mr. Nobody can use to criticize authoritarian regimes when people can symbolize their issues without writing any meaningful words at all. That's why censorship is vain from my point of view.

**Comment by davelab6** [comment]
The main benefit is that the OFL ensures all derivatives are also libre. OFL has no restrictions on usage, so people remain free  to do whatsoever they want with this font.

The OFL is a 'commons', and while someone else can take the font under cc0 and make a fork released under OFL, it would be better if you did this :) 

You could also use both licenses, if you wish

**Comment by sungsit** [comment]
Oh I got it, I missed that point. OFL is not just about my right and it’s good to ensure all derivatives of this font to be free for other people too. Thank you for clarifying that I’ll change it real soon :)

**Comment by sungsit** [comment]
Done.
